dist: xenial
language: python
services:
  - postgresql
python:
  - "3.7"
install:
  - "pip install pipenv"
  - "pipenv install"
before_script:
  - cp config/gapsule.travis.ini config/gapsule.ini
script: 'python -m unittest discover tests'
